[package]
name = "usfx"
version = "0.1.0"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
license = "AGPL-3.0-or-later"
edition = "2018"
readme = "README.md"
repository = "https://github.com/tversteeg/replace_me"
documentation = "https://docs.rs/replace_me"
description = ""
keywords = []
categories = []

[dev-dependencies]
cpal = "0.11.0"
criterion = "0.3.1"
doc-comment = "0.3.3"
sdl2 = "0.33.0"
rust-music-theory = "0.1.6"

[[bench]]
name = "wave_type"
harness = false

[[bench]]
name = "envelope"
harness = false

[[bench]]
name = "mixer"
harness = false
